### ISSUE TITLE
Please read before creating Issue

### ISSUE THREAD

**Issue by ghost1372** [ghost1372/HandyControls#48]
Since this project is based on the official version and receives all its changes, in order to prevent code interference and rework, Please only mention issues related to the unofficial version here and Requests such as new `language packs`, `bugs` and new `features` should be listed on the official page.

**Comment by SamirKharchi** [comment]
So if I wanted to contribute a new feature to a control, I should rather fork from the official version and make a PR there?
But what if I wanted to have the additional stuff from this repository AND my new feature? Will I have to wait until this repository receives my new feature (assuming it was merged) or will any PRs be automatically synced into this repository upon a merge event?

**Comment by SamirKharchi** [comment]
Ok thanks for the info!

**Comment by o-medizadeh-Ard** [comment]
the Growl with prameter 'ShowPersianDateTime = true,' has the following error on date '05/18/2024' :
System.ArgumentOutOfRangeException: 'Year, Month, and Day parameters describe an un-representable DateTime.'
But it works correctly on other dates.

**Comment by ghost1372** [comment]
> the Growl with prameter 'ShowPersianDateTime = true,' has the following error on date '05/18/2024' : System.ArgumentOutOfRangeException: 'Year, Month, and Day parameters describe an un-representable DateTime.' But it works correctly on other dates.

tnx, fixed in https://github.com/ghost1372/HandyControls/commit/905d65b5f6362d47c4ee5d645b01da3f135027a9

**Comment by o-medizadeh-Ard** [comment]
> > the Growl with prameter 'ShowPersianDateTime = true,' has the following error on date '05/18/2024' : System.ArgumentOutOfRangeException: 'Year, Month, and Day parameters describe an un-representable DateTime.' But it works correctly on other dates.
> 
> tnx, fixed in [905d65b](https://github.com/ghost1372/HandyControls/commit/905d65b5f6362d47c4ee5d645b01da3f135027a9)

ok, Thanks.
But the package that is downloaded from 'Nuget' has not been fixed yet and this bug still remains on the latest version 3.5.2.
Thank

**Comment by ghost1372** [comment]
> ok, Thanks. But the package that is downloaded from 'Nuget' has not been fixed yet and this bug still remains on the latest version 3.5.2. Thank

fixed package will be available later. i am busy right now

**Comment by o-medizadeh-Ard** [comment]
> > ok, Thanks. But the package that is downloaded from 'Nuget' has not been fixed yet and this bug still remains on the latest version 3.5.2. Thank
> 
> fixed package will be available later. i am busy right now

Thanks.
I have downloaded and installed the latest '3.5.2' package from nugget.
Please guide me how to use your bug fix commit?

**Comment by ghost1372** [comment]
> > > ok, Thanks. But the package that is downloaded from 'Nuget' has not been fixed yet and this bug still remains on the latest version 3.5.2. Thank
> > 
> > fixed package will be available later. i am busy right now
> 
> Thanks.
> I have downloaded and installed the latest '3.5.2' package from nugget.
> Please guide me how to use your bug fix commit?

I haven't created a new package with the latest fix.
The only way is to compile the project by yourself.

**Comment by o-medizadeh-Ard** [comment]
> > > > ok, Thanks. But the package that is downloaded from 'Nuget' has not been fixed yet and this bug still remains on the latest version 3.5.2. Thank
> > > 
> > > 
> > > fixed package will be available later. i am busy right now
> > 
> > 
> > Thanks.
> > I have downloaded and installed the latest '3.5.2' package from nugget.
> > Please guide me how to use your bug fix commit?
> 
> I haven't created a new package with the latest fix. The only way is to compile the project by yourself.

Our team has developed a project based on this package for 6 months, and now such a problem has occurred during delivery.
Thank you for your efforts in developing this application package
Please update the package.
thanks.

**Comment by ghost1372** [comment]
> > > > > ok, Thanks. But the package that is downloaded from 'Nuget' has not been fixed yet and this bug still remains on the latest version 3.5.2. Thank
> > > > 
> > > > 
> > > > fixed package will be available later. i am busy right now
> > > 
> > > 
> > > Thanks.
> > > I have downloaded and installed the latest '3.5.2' package from nugget.
> > > Please guide me how to use your bug fix commit?
> > 
> > 
> > I haven't created a new package with the latest fix. The only way is to compile the project by yourself.
> 
> Our team has developed a project based on this package for 6 months, and now such a problem has occurred during delivery. Thank you for your efforts in developing this application package Please update the package. thanks.

v3.5.3 uploaded to nuget

**Comment by o-medizadeh-Ard** [comment]
> > > > > > ok, Thanks. But the package that is downloaded from 'Nuget' has not been fixed yet and this bug still remains on the latest version 3.5.2. Thank
> > > > > 
> > > > > 
> > > > > fixed package will be available later. i am busy right now
> > > > 
> > > > 
> > > > Thanks.
> > > > I have downloaded and installed the latest '3.5.2' package from nugget.
> > > > Please guide me how to use your bug fix commit?
> > > 
> > > 
> > > I haven't created a new package with the latest fix. The only way is to compile the project by yourself.
> > 
> > 
> > Our team has developed a project based on this package for 6 months, and now such a problem has occurred during delivery. Thank you for your efforts in developing this application package Please update the package. thanks.
> 
> v3.5.3 uploaded to nuget

Thank you very much.

**Comment by GF-Huang** [comment]
@ghost1372 How did you sync HC (`HandyControl`) to this repo (HCS - `HandyControls`)? I had try GitHub Pull Requests, it seems not supports PR from/to different repo. I want to merge some PR from HC into custom branch of my HCS fork and compile by myself.

**Comment by GF-Huang** [comment]
Oh I solve it. Just add HCS as new remote of HC in local git, then push PR branches to HCS.

**Comment by GF-Huang** [comment]
@ghost1372 How did you build from powershell? I got `Error: Failed to install addin 'Cake.Git'.`.

![image](https://github.com/ghost1372/HandyControls/assets/4510984/80bd80a5-6f6e-49d6-bb49-5d9bc66dde2c)
